print("Kehidupan kampus penuh dengan dinamika dan tantangan.")
print("Mahasiswa belajar untuk mengembangkan diri, baik akademis maupun non-akademis.")
print("Setiap hari adalah kesempatan baru untuk bertemu teman dan bertukar ide.") 
print("Kegiatan organisasi dan komunitas membentuk keterampilan sosial yang berharga.")
print("Di antara jadwal yang padat, mahasiswa juga belajar manajemen waktu.")
print("Kampus adalah tempat di mana masa depan direncanakan.") 